spring:
  application:
    name: todo
  mvc:
    pathmatch:
      use-registered-suffix-pattern: true
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/todobear?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root

server:
  port: 9999

management:
  server:
    port: 9991
  endpoints:
    jmx:
      exposure:
        include: '*'
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.bear.todo.model


logging:
  level:
    com:
      bear:
        todo: debug

